Add "Skip to main content" link to default layout
BKWLD/create-cloak-app pull request #23
Opened 2021-09-03 20:45 UTC by jonjahr

I tried to keep it simple.  It's a mostly unstyled link, positioned offscreen.  When focused, it appears in the top left immediately below the top nav.  I opted to put it below the nav and not inside the nav, because below tablet the logo usually occupies the top left and I don't want them to collide.

![Kapture 2021-09-03 at 13 38 43](https://user-images.githubusercontent.com/6802815/132063092-7441ef5b-f7e3-48b2-b2b7-e5bfa2cbe025.gif)

2021-09-04 03:32 UTC, weotch requested changes
Watcha think about these changes?

2021-09-04 03:32 UTC, weotch commented on template/nuxt-app/layouts/default.vue
> +	top (header-h + 10px)
How about

```suggestion
	+tablet-up()
		top (header-h + spacing-s)
	+tablet-down()
		top (header-h-mobile + spacing-s-min)
```

2021-09-04 03:32 UTC, weotch commented on template/nuxt-app/layouts/default.vue
> +		left 10px
```suggestion
		fluid left, gutter, gutter-mobile
```

2021-09-05 16:14 UTC, jonjahr commented
Good improvements.  I applied them.

2021-09-07 15:53 UTC, merged